### ISSUE TITLE
hello brother

### ISSUE THREAD

**Issue by glerinsonum** [elcoc0/fbscraper#1]
@elcoc0 Do you have any file.py example 

python get_location.py -i ( id photo or id video ) 2392392392

longitude: 29229292.222 
latitude: 18218181.2323 

thank

**Comment by elcoc0** [comment]
Hey glerinsonum,

When you upload a photo on Facebook, EXIF data is erased, so there is no metadata on it. You could maybe get it from Facebook post that do have localisation enable and a photo attached, but it is at the moment beyond what my tool provide (only data from conversations).

Cheers

**Comment by glerinsonum** [comment]
Understand :) 

I would like to find any way for to delete this article post via url 
https://www.facebook.com/thurje/videos/578935742315598/
How I can do this.

**Comment by glerinsonum** [comment]
I have demonstred with Graph API Explorer, via Access Token ID of App and Extended Access
With two scopes. Nothing. I do no how I can make an scopes "example" delete_content "delete_video"

**Comment by glerinsonum** [comment]
@elcoc0 Brother of Good, this post "facebook scaper" is an information gathering tool ?

**Comment by glerinsonum** [comment]
Thank @elcoc0 for your warm response. 
Can tell me, what is this "fbscaper"

**Comment by elcoc0** [comment]
You could find all the information on the README.md file.

You can download all or specific conversations from your account which is formatted in JSON, not very human-friendly. 
Than you can parse all you downloaded JSON conversations to report or even download specific information you are looking for (messages, videos, images, links, files...). It can also parse all your conversations automatically. 

You should give it a try, it does the job quiet nicely !
