### ISSUE TITLE
hi brother

### ISSUE THREAD

**Issue by glerinsonum** [elcoc0/fbscraper#2]
@elcoc0 only those can get messages, pictures, gifs, videos, files. 

longitude & latitude to see his location there 
and what version python should for fb scapper. and how i can install requirements.txt

**Comment by elcoc0** [comment]
Get a python 3 installation using your package manager. Then just clone the repository and execute these commands : 

```
pip3 install -r requirements.txt
pip3 install dist/fbscraper-0.1-py3-none-any.whl
```

**Comment by glerinsonum** [comment]
**Thanks** 
@elcoc0 But, What's opportunities offer's those scripts.

**Comment by elcoc0** [comment]
glerinsonum,

You can dump all your FB conversations. Parse and download all pictures, videos, links, files from these conversations.

You can find all this information from the repository README.md file.

Cheers
